// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBBOxwiVgV6r1d0xSZRHTdHX7AkX9pP5Q',
    appId: '1:451873947536:web:f2bcb10a1b0acb7493fd15',
    messagingSenderId: '451873947536',
    projectId: 'edefinir-bd3ed',
    authDomain: 'edefinir-bd3ed.firebaseapp.com',
    storageBucket: 'edefinir-bd3ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUBNtq7l-gJB9bdHSjy1B0y100UInst70',
    appId: '1:451873947536:android:d3eb95248c178c1593fd15',
    messagingSenderId: '451873947536',
    projectId: 'edefinir-bd3ed',
    storageBucket: 'edefinir-bd3ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN2mYqo8cjs9Kt0j0E3g_kKxpMG07Gqtg',
    appId: '1:451873947536:ios:39850cd801daf76a93fd15',
    messagingSenderId: '451873947536',
    projectId: 'edefinir-bd3ed',
    storageBucket: 'edefinir-bd3ed.appspot.com',
    iosBundleId: 'com.example.edefinir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN2mYqo8cjs9Kt0j0E3g_kKxpMG07Gqtg',
    appId: '1:451873947536:ios:8552b1446658189893fd15',
    messagingSenderId: '451873947536',
    projectId: 'edefinir-bd3ed',
    storageBucket: 'edefinir-bd3ed.appspot.com',
    iosBundleId: 'com.example.edefinir.RunnerTests',
  );
}
