// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4nwNrkleeBRe0oUC0glEZATsNm4CH13g',
    appId: '1:218649542174:web:c5f4aa024ca19226b4780f',
    messagingSenderId: '218649542174',
    projectId: 'projeto-edefinir',
    authDomain: 'projeto-edefinir.firebaseapp.com',
    storageBucket: 'projeto-edefinir.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpUN3OIULAv5UP2wP0uucN-BMdZMSLyIY',
    appId: '1:218649542174:android:5c59bcd520fe3081b4780f',
    messagingSenderId: '218649542174',
    projectId: 'projeto-edefinir',
    storageBucket: 'projeto-edefinir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu1e7Tj32PBpOKnRLHIkwHatePs9pPD6Y',
    appId: '1:218649542174:ios:97345755942651f1b4780f',
    messagingSenderId: '218649542174',
    projectId: 'projeto-edefinir',
    storageBucket: 'projeto-edefinir.appspot.com',
    iosBundleId: 'com.example.edefinir',
  );
}
